### ISSUE TITLE
Doesn't seems to work with Safari 7.0.6 / OSX 10.9.4

### ISSUE THREAD

**Issue by Gomme** [jaydorsey/Personal-Search-Result-Blocker#1]
Hi,
I was looking for a Personal Blocklist alternative.
I've tested some user script and an obscur japanese safari extension, nothing works.
So I just tried your extension because it looks serious and recent, and DAMN, it doesn't works too. :(
Any chance to make it works on a up-to-date Safari ? :rose: It could be really awesome because it seems there's no alternative solution to Personal Blocklist at this moment.

![capture d ecran 2014-08-23 a 11 20 05](https://cloud.githubusercontent.com/assets/1690413/4020145/9c85526a-2aa7-11e4-9167-3f74d86849c0.png)

**Comment by cazepeda** [comment]
Any updates?

**Comment by jaydorsey** [comment]
Sorry, I haven't taken a look at improvements to Safari Extensions in a while. I've been focused on Linux/Ruby on Rails/Elixir of late. What version of Safari are you running? I might be able to do some updates to get it working in the latest 8.0.8 on Yosemite (my machine) but I don't have the ability to test on other versions.

**Comment by Gomme** [comment]
For me : 10.10.4 + Safari 8.0.7

**Comment by jaydorsey** [comment]
I had some time to look at this over the holidays. I'm going to mark this as contributions welcome and close the ticket. I'll update the README to make it clear that it's not functioning on newer versions of Safari, was a personal project, and is no longer maintained.

I don't have the time or enthusiasm to continue working on this, in addition to my other projects (personal and work related)

I've long since switched over to using Chrome as my daily browser and only touch Safari on iOS. I use and develop for Chrome at work (have to develop on Windows for now) and I grew fond enough of it that I switched. There's a rich set of plugins available for Chrome, including a personal blocklist (which is where I got the idea from)
